# Generated by Django 2.1.4 on 2018-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languagecodes',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('languagecode', models.TextField()),
                ('languagetext', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'languagecodes',
                'managed': False,
            },
        ),
    ]
