# Generated by Django 2.1.4 on 2018-12-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_patches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('partype', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'champions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemdescriptions',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemdescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itemdescriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemnames',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itemnames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('instore', models.BooleanField(blank=True, null=True)),
                ('basegold', models.IntegerField(blank=True, null=True)),
                ('purchasable', models.BooleanField(blank=True, null=True)),
                ('totalgold', models.IntegerField(blank=True, null=True)),
                ('sellgold', models.IntegerField(blank=True, null=True)),
                ('hidefromall', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
    ]
