# Generated by Django 2.1.4 on 2018-12-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0003_champions_itemdescriptions_itemnames_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemplaintexts',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('plaintext', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itemplaintexts',
                'managed': False,
            },
        ),
    ]
