# Generated by Django 2.1.4 on 2018-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0005_itemmaps_itemstats_itemtags_languageitems_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemeffects',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('effectindex', models.IntegerField(blank=True, null=True)),
                ('effectvalue', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itemeffects',
                'managed': False,
            },
        ),
    ]
