# Generated by Django 2.1.4 on 2018-12-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0008_itembuiltfroms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemimages',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullurl', models.TextField(blank=True, null=True)),
                ('spriteurl', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('w', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itemimages',
                'managed': False,
            },
        ),
    ]
